# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8250-common-gourami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sm8250-common-gourami)

endif
